---
ci:
  skip: ["mypy"]
  autofix_prs: false
default_language_version:
  python: "python3"
fail_fast: false

repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v4.5.0"
    hooks:
      - id: "check-added-large-files"
        args: ["--maxkb=40000"]
      - id: "check-ast"
      - id: "check-byte-order-marker"
      - id: "check-case-conflict"
      - id: "check-docstring-first"
      - id: "check-executables-have-shebangs"
      - id: "check-json"
      - id: "check-symlinks"
      - id: "check-merge-conflict"
      - id: "check-vcs-permalinks"
      - id: "check-xml"
      - id: "check-yaml"
      - id: "debug-statements"
      - id: "end-of-file-fixer"
        exclude: ".+\\.ipynb"
      - id: "mixed-line-ending"
      - id: "name-tests-test"
      - id: "trailing-whitespace"

  - repo: "https://github.com/pre-commit/pygrep-hooks"
    rev: "v1.10.0"
    hooks:
      - id: "python-check-blanket-noqa"
      - id: "python-check-blanket-type-ignore"
      - id: "python-use-type-annotations"

  - repo: "https://github.com/asottile/reorder_python_imports"
    rev: "v3.12.0"
    hooks:
      - id: "reorder-python-imports"
        args:
          - "--py310-plus"
          - "--add-import"
          - "from __future__ import annotations"

  - repo: "https://github.com/asottile/add-trailing-comma"
    rev: "v3.1.0"
    hooks:
      - id: "add-trailing-comma"

  - repo: "https://github.com/astral-sh/ruff-pre-commit"
    rev: "v0.1.7"
    hooks:
      - id: "ruff"
        args: ["--show-fixes"]
      - id: "ruff-format"

  - repo: "https://github.com/python-poetry/poetry"
    rev: "1.7.0"
    hooks:
      - id: "poetry-check"
        name: "poetry check"
      - id: "poetry-check"
        name: "poetry check --lock"
        args: ["--lock"]
      - id: "poetry-lock"
        name: "poetry lock --no-update"
        args: ["--no-update"]
      - id: "poetry-export"
        name: "poetry export main"
        args:
          [
            "--without-hashes",
            "-f",
            "requirements.txt",
            "--only",
            "main",
            "-o",
            "requirements/requirements.txt",
          ]
      - id: "poetry-export"
        name: "poetry export dev"
        args:
          [
            "--without-hashes",
            "-f",
            "requirements.txt",
            "--with",
            "dev",
            "-o",
            "requirements/requirements-dev.txt",
          ]

  - repo: "local"
    hooks:
      - id: "mypy"
        name: "mypy"
        entry: "make mypy"
        language: "system"
        types: ["python"]
